### ISSUE TITLE
XtremIO Code Upgrade

### ISSUE THREAD

**Issue by hroman73** [dmuegge/MTSXtremIO#1]
Good morning, we performed a code upgrade to 4.0.2-80 on our XtremIO over the weekend. We had an automated script that would renew snaps every day and since the upgrade MTSXtremIO is unable to unmap, create new snaps and map.

**Comment by dmuegge** [comment]
hroman73,

Thanks for the heads up, appreciated. I am not running that version yet. I will try to get my lab updated ASAP to take a look at this. Can you verify for me that you are using the .44 pre-release version of the module?

Also, if you can elaborate and provide any additional information, it is appreciated.

Thanks,

Dave

**Comment by hroman73** [comment]
Right when the script started to fail I downloaded the latest version. Here are the commands and the errors:

`Remove-XIOSnapshot` -Name `"Server-Snap"`

> Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
> At C:\Users\veritas\Documents\WindowsPowerShell\Modules\MTSXtremIO\MTSXtremIO.psm1:5105 char:21
> -                     Invoke-RestMethod -Method Delete -Uri ($Global:XIOAPIBaseUri ...
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
>   - FullyQualifiedErrorId : 
> 
> WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

`New-XIOLunMap -InitiatorGroup Server-IG -Name`Server-Snap`

> Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
> At C:\Users\veritas\Documents\WindowsPowerShell\Modules\MTSXtremIO\MTSXtremIO.psm1:3469 char:17
> -                 Invoke-RestMethod -Method Post -Uri ($Global:XIOAPIBaseUri + $Ur ...
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
>   - FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by hroman73** [comment]
I found the problem where in the new code 4.02-80 XtremIO now inserts the "." before the snapshot suffix. The old script resulted in ".." 

The script is now running as designed...
